services:
  frontend:
    build:
      context: ./apps
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true # hot-reload (for window)

networks:
  algosync-network:
    driver: bridge
