services:
  frontend:
    build:
      context: ./apps
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true # hot-reload (for window)
    networks:
      - algosync-network

  auth:
    build:
      context: ./services/auth
    container_name: auth-service
    ports:
      - "4000:4000"
    volumes:
      - ./services/auth:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    networks:
      - algosync-network
  
  db:
    image: postgres:16
    container_name: algosync_postgres
    restart: always
    environment:
      POSTGRES_USER: algosync_user
      POSTGRES_PASSWORD: algosync_pass
      POSTGRES_DB: algosync_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - algosync-network

networks:
  algosync-network:
    driver: bridge

volumes:
  pgdata:
