services:
  frontend:
    build:
      context: ./apps
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true # hot-reload (for window)

  # AI-service:
  #   build: ./Services/AI-service/
  #   ports:
  #     - "5001:5000"
  #   networks:
  #     - algosync-network

networks:
  algosync-network:
    driver: bridge
